using ClaimsService.EDI.Inbound;
using CloudHealthOffice.ClaimsScrubEngine.Models;
using Xunit;

namespace CloudHealthOffice.ClaimsService.Tests.EDI;

/// <summary>
/// Verified against two real 837P samples generated by this repo's own
/// tested EDI writers — not hand-authored fixtures — specifically because
/// they turned out to disagree with each other on structure (HL loops
/// present vs. absent, SV1's diagnosis-pointer element index) and that
/// disagreement is exactly the kind of real-world variance an inbound
/// parser has to tolerate.
/// </summary>
public class X12837ParserTests
{
    // Generated by FmmisClaimTransformer.BuildEdi with ClaimType.Institutional
    // — real SV2 (revenue code + procedure composite) service lines, not
    // hand-authored. Confirms SV2's layout genuinely differs from SV1
    // (revenue code occupies index 0, pushing the procedure composite to
    // index 1) rather than being a simple index shift.
    private const string FmmisInstitutionalSample =
        "ISA*00*          *00*          *ZZ*FLMCO00001     *ZZ*FMMIS          *260725*0605*^*00501*000000001*0*P*:~GS*HC*FLMCO00001*FMMIS*20260725*0605*1*X*005010X223A3~ST*837*0001*005010X223A3~BHT*0019*18*E2E-FL-INST-0001*20260725*0605*CH~NM1*41*2*E2E FL HOSPITAL*****46*FLMCO00001~PER*IC*FMMIS ENCOUNTER SUBMISSION*TE*0000000000~NM1*40*2*FLORIDA MEDICAID FMMIS*****46*FMMIS~HL*1**20*1~NM1*85*2*E2E FL HOSPITAL*****XX*1234567890~N3*ADDRESS ON FILE~N4*CITY*FL*00000~REF*1D*FL-MCD-00001~HL*2*1*22*0~SBR*P*18*****MC~NM1*IL*1*PATIENT*TEST****MI*MBR-INST-SAMPLE~NM1*PR*2*FLORIDA MEDICAID*****PI*FMMIS~CLM*E2E-FL-INST-0001*5000.00***21:B:1*Y*A*Y*Y~DTP*434*RD8*20260722-20260725~HI*ABK:J18.9~LX*1~SV2*0120*HC:99231*3000.00*UN*3~DTP*472*RD8*20260722-20260725~LX*2~SV2*0320*HC:71045*2000.00*UN*1~DTP*472*RD8*20260722-20260722~SE*24*0001~GE*1*1~IEA*1*000000001~";

    // Generated by FmmisClaimTransformer.BuildEdi — full HL hierarchy
    // (2000A billing provider -> 2000B subscriber), subscriber is the
    // patient (HL04=0, no 2000C dependent loop), single "~"-terminated line.
    private const string FmmisHlSample =
        "ISA*00*          *00*          *ZZ*FLMCO00001     *ZZ*FMMIS          *260725*0518*^*00501*000000001*0*P*:~GS*HC*FLMCO00001*FMMIS*20260725*0518*1*X*005010X222A1~ST*837*0001*005010X222A1~BHT*0019*18*E2E-FL-SAMPLE-0001*20260725*0518*CH~NM1*41*2*E2E FL SPECIALIST GROUP*****46*FLMCO00001~PER*IC*FMMIS ENCOUNTER SUBMISSION*TE*0000000000~NM1*40*2*FLORIDA MEDICAID FMMIS*****46*FMMIS~HL*1**20*1~NM1*85*2*E2E FL SPECIALIST GROUP*****XX*1234567890~N3*ADDRESS ON FILE~N4*CITY*FL*00000~REF*1D*FL-MCD-00001~HL*2*1*22*0~SBR*P*18*****MC~NM1*IL*1*MEMBER*TEST****MI*MBR19-SAMPLE~NM1*PR*2*FLORIDA MEDICAID*****PI*FMMIS~CLM*E2E-FL-SAMPLE-0001*200.00***11:B:1*Y*A*Y*Y~DTP*472*RD8*20260725-20260725~HI*ABK:J06.9~LX*1~SV1*HC:99213*150.00*UN*1*11**1~DTP*472*RD8*20260725-20260725~SE*21*0001~GE*1*1~IEA*1*000000001~";

    // Same shape as FmmisHlSample — mirrors the 837 payload embedded in
    // scripts/smoke/834-to-837-e2e-smoke.sh (member id BSCA123456789 there
    // matches REF*0F in docs/testing/test-x12-834-enrollment-sample.edi,
    // the 834 fixture that script imports first). Keep this in sync with
    // the script if either changes — this test is what proves the
    // hand-authored shell fixture actually parses before anyone runs it
    // against a live stack.
    private const string SmokeTest834To837Sample =
        "ISA*00*          *00*          *ZZ*SMOKESENDER    *ZZ*SMOKERECEIVER  *260101*0000*^*00501*000000001*0*P*:~GS*HC*SMOKESENDER*SMOKERECEIVER*20260101*0000*1*X*005010X222A1~ST*837*0001*005010X222A1~BHT*0019*18*SMOKE-834837-0001*20260101*0000*CH~NM1*41*2*SMOKE SUBMITTER*****46*SMOKESENDER~PER*IC*SMOKE SUBMITTER*TE*0000000000~NM1*40*2*SMOKE RECEIVER*****46*SMOKERECEIVER~HL*1**20*1~NM1*85*2*SMOKE MEDICAL GROUP*****XX*1234567890~N3*ADDRESS ON FILE~N4*SAN FRANCISCO*CA*94102~HL*2*1*22*0~SBR*P*18*****CI~NM1*IL*1*SMITH*JOHN****MI*BSCA123456789~NM1*PR*2*SMOKE PAYER*****PI*SMOKEPAYER~CLM*SMOKE-834837-0001*150.00***11:B:1*Y*A*Y*Y~DTP*472*RD8*20260101-20260101~HI*ABK:J06.9~LX*1~SV1*HC:99213*150.00*UN*1*11**1~DTP*472*RD8*20260101-20260101~SE*17*0001~GE*1*1~IEA*1*000000001~";

    // Generated by EncounterTransformer/EncounterBatchBuilder — no HL
    // loops at all (flat SBR-only), newline-terminated, two claims in one
    // batch with different billing providers/subscribers, and a rendering
    // provider (NM1*82) attached to the first claim only.
    private const string EncounterEngineBatchSample = """
        ISA*00*          *00*          *ZZ*PLAN001        *ZZ*CMS001         *260725*0517*^*00501*000000001*0*P*:
        GS*HC*PLAN001APP*CMS001APP*20260725*0517*1*X*005010X222A2
        ST*837*111746392*005010X222A2
        BHT*0019*00*111746392*20260725*0517*CH
        NM1*41*2*Test Health Plan*****XX*PLAN001
        PER*IC*EDI CONTACT*TE*0000000000
        NM1*40*2*RECEIVER*****46*CMS001
        NM1*85*2*ACME MEDICAL GROUP*****XX*1234567890
        REF*EI*123456789
        SBR*P*18*SUB1001***HM**MB
        NM1*IL*1*Doe*Jane****MI*MEM1001
        DMG*D8*19800615*F
        NM1*PR*2*Test Health Plan*****PI*88888
        CLM*CLM1001*250.00***11::B*Y*A*Y*I
        DTP*472*D8*20260310
        HI*ABK:Z00.00*ABF:E119
        AMT*AU*160.00
        AMT*NE*40.00
        MOA***160.00
        NM1*82*1*WELBY*MARCUS***XX*1122334455
        LX*1
        SV1*HC:99213*200.00*UN*1**1
        DTP*472*D8*20260310
        AMT*AU*128.00
        AMT*B6*160.00
        AMT*A1*12.00
        AMT*F4*20.00
        LX*2
        SV1*HC:85025*50.00*UN*1**2
        DTP*472*D8*20260310
        AMT*AU*32.00
        AMT*B6*40.00
        SE*31*111746392
        ST*837*762198567*005010X222A2
        BHT*0019*00*762198567*20260725*0517*CH
        NM1*41*2*Test Health Plan*****XX*PLAN001
        PER*IC*EDI CONTACT*TE*0000000000
        NM1*40*2*RECEIVER*****46*CMS001
        NM1*85*2*JONES FAMILY PRACTICE*****XX*9876543219
        REF*EI*987654321
        SBR*P*18*SUB1002***HM**MB
        NM1*IL*1*Johnson*Robert****MI*MEM1002
        DMG*D8*19900522*M
        NM1*PR*2*Test Health Plan*****PI*88888
        CLM*CLM1002*200.00***11::B*Y*A*Y*I
        DTP*472*D8*20260312
        HI*ABK:I10
        AMT*AU*60.00
        AMT*NE*20.00
        OI***Y**Y*Y
        NM1*TT*2*MEDICARE*****PI*MCARE01
        AMT*D*80.00
        MOA***60.00
        LX*1
        SV1*HC:99214*200.00*UN*1**1
        DTP*472*D8*20260312
        AMT*AU*60.00
        AMT*B6*160.00
        AMT*D*80.00
        SE*27*762198567
        GE*2*1
        IEA*1*000000001
        """;

    // ── FMMIS: full HL hierarchy, subscriber-is-patient ────────────────

    [Fact]
    public void Parse_FmmisSample_ProducesOneClaim()
    {
        var claims = X12837Parser.Parse(FmmisHlSample);
        Assert.Single(claims);
    }

    [Fact]
    public void Parse_FmmisSample_SubscriberIsPatient_PatientStaysNull()
    {
        // HL04=0 on the 2000B subscriber loop means no 2000C dependent —
        // the subscriber IS the patient. Patient must stay null, not get
        // populated with the subscriber's own data.
        var claim = X12837Parser.Parse(FmmisHlSample)[0];
        Assert.Null(claim.Patient);
    }

    [Fact]
    public void Parse_FmmisSample_BillingProviderAndSubscriber()
    {
        var claim = X12837Parser.Parse(FmmisHlSample)[0];

        Assert.Equal("1234567890", claim.BillingProvider.Npi);
        Assert.Equal("E2E FL SPECIALIST GROUP", claim.BillingProvider.Name);
        Assert.Equal("ADDRESS ON FILE", claim.BillingProvider.Address.Line1);
        Assert.Equal("CITY", claim.BillingProvider.Address.City);
        Assert.Equal("FL", claim.BillingProvider.Address.State);

        Assert.Equal("MBR19-SAMPLE", claim.Subscriber.MemberId);
        Assert.Equal("MEMBER", claim.Subscriber.LastName);
        Assert.Equal("TEST", claim.Subscriber.FirstName);
    }

    [Fact]
    public void Parse_FmmisSample_ClaimHeaderAndDiagnosis()
    {
        var claim = X12837Parser.Parse(FmmisHlSample)[0];

        Assert.Equal("E2E-FL-SAMPLE-0001", claim.ClaimHeader.PatientControlNumber);
        Assert.Equal(200.00m, claim.ClaimHeader.TotalChargeAmount);
        Assert.Equal("11", claim.ClaimHeader.PlaceOfServiceCode);
        Assert.Equal("1", claim.ClaimHeader.FrequencyCode);
        Assert.Equal("J06.9", claim.ClaimHeader.PrincipalDiagnosisCode);
        Assert.Single(claim.ClaimHeader.DiagnosisCodes!);
        Assert.Equal("ABK", claim.ClaimHeader.DiagnosisCodes![0].Qualifier);
    }

    [Fact]
    public void Parse_FmmisSample_ServiceLine_UsesSpecCorrectDiagnosisPointerIndex()
    {
        // SV1*HC:99213*150.00*UN*1*11**1 — place of service at index 4,
        // diagnosis pointer at index 6 (the spec-correct position).
        var claim = X12837Parser.Parse(FmmisHlSample)[0];
        var line = Assert.Single(claim.ServiceLines);

        Assert.Equal("99213", line.ProcedureCode);
        Assert.Equal(150.00m, line.ChargeAmount);
        Assert.Equal("11", line.PlaceOfService);
        Assert.Equal([1], line.DiagnosisPointers);
        Assert.Equal("20260725", line.ServiceDate);
        Assert.Equal("20260725", line.ServiceDateEnd);
    }

    // ── 834-to-837 smoke script fixture ─────────────────────────────────

    [Fact]
    public void Parse_SmokeTestSample_ParsesToExpectedMemberAndServiceLine()
    {
        // Guards scripts/smoke/834-to-837-e2e-smoke.sh's embedded 837 —
        // if this ever stops parsing, that script would fail with a cryptic
        // curl error instead of a clear "your fixture is malformed" signal.
        var claim = X12837Parser.Parse(SmokeTest834To837Sample)[0];

        Assert.Equal("BSCA123456789", claim.Subscriber.MemberId);
        Assert.Null(claim.Patient);

        var line = Assert.Single(claim.ServiceLines);
        Assert.Equal("99213", line.ProcedureCode);
        Assert.Equal(150.00m, line.ChargeAmount);
        Assert.Equal("11", line.PlaceOfService);
    }

    [Fact]
    public void Map_SmokeTestSample_ProducesClaimResolvableAgainstThe834FixtureMember()
    {
        // The end-to-end proof this smoke test needs: the mapped
        // AdapterClaim.MemberId must equal REF*0F from
        // docs/testing/test-x12-834-enrollment-sample.edi (the subscriber
        // the 834 half of the script creates as "BSCA123456789") so
        // ClaimAdjudicationOrchestrator's coverage lookup has a real member
        // to resolve against.
        var parsed = X12837Parser.Parse(SmokeTest834To837Sample)[0];
        var claim = X12837ClaimMapper.Map(parsed, "tenant-smoke-834-837");

        Assert.Equal("BSCA123456789", claim.MemberId);
        Assert.Equal(global::ClaimsService.Models.ClaimType.Professional, claim.ClaimType);
        Assert.Null(claim.BenefitPlanId);
        Assert.Equal("11", claim.PlaceOfServiceCode);
    }

    // ── EncounterEngine: no HL loops, two claims, differing SV1 shape ──

    [Fact]
    public void Parse_EncounterEngineBatch_ProducesBothClaimsWithoutAnyHlSegments()
    {
        var claims = X12837Parser.Parse(EncounterEngineBatchSample);

        Assert.Equal(2, claims.Count);
        Assert.All(claims, c => Assert.Null(c.Patient));
    }

    [Fact]
    public void Parse_EncounterEngineBatch_EachClaimGetsItsOwnBillingProviderAndSubscriber()
    {
        // Regression guard for the exact class of bug the Indice.Edi spike
        // hit: claim 2's billing provider/subscriber must not leak claim
        // 1's data, and vice versa.
        var claims = X12837Parser.Parse(EncounterEngineBatchSample);

        Assert.Equal("ACME MEDICAL GROUP", claims[0].BillingProvider.Name);
        Assert.Equal("123456789", claims[0].BillingProvider.TaxId);
        Assert.Equal("Doe", claims[0].Subscriber.LastName);
        Assert.Equal("MEM1001", claims[0].Subscriber.MemberId);
        Assert.Equal("19800615", claims[0].Subscriber.DateOfBirth);

        Assert.Equal("JONES FAMILY PRACTICE", claims[1].BillingProvider.Name);
        Assert.Equal("987654321", claims[1].BillingProvider.TaxId);
        Assert.Equal("Johnson", claims[1].Subscriber.LastName);
        Assert.Equal("MEM1002", claims[1].Subscriber.MemberId);
    }

    [Fact]
    public void Parse_EncounterEngineBatch_TransactionControlNumberTracksEachStSegment()
    {
        var claims = X12837Parser.Parse(EncounterEngineBatchSample);

        Assert.Equal("111746392", claims[0].TransactionControlNumber);
        Assert.Equal("762198567", claims[1].TransactionControlNumber);
    }

    [Fact]
    public void Parse_EncounterEngineBatch_RenderingProvider_AttachesOnlyToTheClaimItFollows()
    {
        var claims = X12837Parser.Parse(EncounterEngineBatchSample);

        Assert.NotNull(claims[0].ClaimHeader.RenderingProvider);
        Assert.Equal("1122334455", claims[0].ClaimHeader.RenderingProvider!.Npi);
        Assert.Null(claims[1].ClaimHeader.RenderingProvider);
    }

    [Fact]
    public void Parse_EncounterEngineBatch_ServiceLines_FallBackToIndexFiveDiagnosisPointer()
    {
        // SV1*HC:99213*200.00*UN*1**1 — this generator omits SV105/106
        // entirely, so the diagnosis pointer lands at index 5, not the
        // spec-correct index 6. The parser must still find it.
        var claim = claims_First();
        Assert.Equal(2, claim.ServiceLines.Count);

        Assert.Equal("99213", claim.ServiceLines[0].ProcedureCode);
        Assert.Equal(200.00m, claim.ServiceLines[0].ChargeAmount);
        Assert.Null(claim.ServiceLines[0].PlaceOfService); // this generator never sets it
        Assert.Equal([1], claim.ServiceLines[0].DiagnosisPointers);
        Assert.Equal("20260310", claim.ServiceLines[0].ServiceDate);

        Assert.Equal("85025", claim.ServiceLines[1].ProcedureCode);
        Assert.Equal([2], claim.ServiceLines[1].DiagnosisPointers);

        static X12837Claim claims_First() => X12837Parser.Parse(EncounterEngineBatchSample)[0];
    }

    [Fact]
    public void Parse_EncounterEngineBatch_DiagnosisCodes_PerClaim()
    {
        var claims = X12837Parser.Parse(EncounterEngineBatchSample);

        Assert.Equal(2, claims[0].ClaimHeader.DiagnosisCodes!.Count);
        Assert.Equal("Z00.00", claims[0].ClaimHeader.DiagnosisCodes![0].Code);
        Assert.Equal("E119", claims[0].ClaimHeader.DiagnosisCodes![1].Code);

        Assert.Single(claims[1].ClaimHeader.DiagnosisCodes!);
        Assert.Equal("I10", claims[1].ClaimHeader.DiagnosisCodes![0].Code);
    }

    // ── FMMIS institutional: SV2, not SV1 ──────────────────────────────

    [Fact]
    public void Parse_InstitutionalSample_DetectsClaimTypeFromStVersion()
    {
        var claim = X12837Parser.Parse(FmmisInstitutionalSample)[0];
        Assert.Equal(ClaimType.Institutional, claim.ClaimType);
    }

    [Fact]
    public void Parse_InstitutionalSample_ServiceLines_UseRevenueCodeAndShiftedProcedureIndex()
    {
        // SV2*0120*HC:99231*3000.00*UN*3 — revenue code at index 0 (SV1 has
        // no equivalent slot), which pushes the procedure composite to
        // index 1 instead of SV1's index 0.
        var claim = X12837Parser.Parse(FmmisInstitutionalSample)[0];
        Assert.Equal(2, claim.ServiceLines.Count);

        Assert.Equal("0120", claim.ServiceLines[0].RevenueCode);
        Assert.Equal("99231", claim.ServiceLines[0].ProcedureCode);
        Assert.Equal("HC", claim.ServiceLines[0].ProcedureCodeQualifier);
        Assert.Equal(3000.00m, claim.ServiceLines[0].ChargeAmount);
        Assert.Equal(3, claim.ServiceLines[0].Units);

        Assert.Equal("0320", claim.ServiceLines[1].RevenueCode);
        Assert.Equal("71045", claim.ServiceLines[1].ProcedureCode);
        Assert.Equal(2000.00m, claim.ServiceLines[1].ChargeAmount);
    }

    [Fact]
    public void Parse_InstitutionalSample_TotalChargeAndDiagnosis()
    {
        var claim = X12837Parser.Parse(FmmisInstitutionalSample)[0];

        Assert.Equal(5000.00m, claim.ClaimHeader.TotalChargeAmount);
        Assert.Equal("J18.9", claim.ClaimHeader.PrincipalDiagnosisCode);
        Assert.Equal("E2E FL HOSPITAL", claim.BillingProvider.Name);
    }

    // ── Malformed input ─────────────────────────────────────────────────

    [Fact]
    public void Parse_RejectsContentThatIsNotX12()
    {
        Assert.Throws<X12FormatException>(() => X12837Parser.Parse("not an edi file"));
    }
}
