apiVersion: v1
kind: Secret
metadata:
  name: claims-service-secret
  namespace: cloudhealthoffice
type: Opaque
stringData:
  MongoDb__ConnectionString: "mongodb://admin:securepassword123@mongodb:27017"
  MongoDb__DatabaseName: "CloudHealthOffice"
  CosmosDb__Endpoint: "https://placeholder-cosmos"
  CosmosDb__Key: "placeholder-key"
