<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ConsentService</RootNamespace>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <AzureCosmosDisableNewtonsoftJsonCheck>true</AzureCosmosDisableNewtonsoftJsonCheck>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="ConsentService.Tests/**" />
    <Content Remove="ConsentService.Tests/**" />
    <None Remove="ConsentService.Tests/**" />
    <EmbeddedResource Remove="ConsentService.Tests/**" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ConsentService.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\shared\CloudHealthOffice.Infrastructure\CloudHealthOffice.Infrastructure.csproj" />
    <ProjectReference Include="..\shared\CloudHealthOffice.Consent.Contracts\CloudHealthOffice.Consent.Contracts.csproj" />
    <PackageReference Include="Confluent.Kafka" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Azure.Cosmos" />
    <PackageReference Include="MongoDB.Driver" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

</Project>
