using Microsoft.AspNetCore.Mvc;
using CapitationService.Models;
using CapitationService.Repositories;
using CapitationService.Services;

namespace CapitationService.Controllers;

[ApiController]
[Route("api/v1/capitation/runs")]
[Produces("application/json")]
public class CapitationRunsController : ControllerBase
{
    private readonly ICapitationRunService _runService;
    private readonly ICapitationStatementRepository _statementRepository;
    private readonly ILogger<CapitationRunsController> _logger;

    public CapitationRunsController(
        ICapitationRunService runService,
        ICapitationStatementRepository statementRepository,
        ILogger<CapitationRunsController> logger)
    {
        _runService = runService;
        _statementRepository = statementRepository;
        _logger = logger;
    }

    /// <summary>
    /// Create a new capitation run (does not execute)
    /// </summary>
    [HttpPost]
    [ProducesResponseType(typeof(CapitationRun), StatusCodes.Status201Created)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<CapitationRun>> CreateRun([FromBody] CreateCapitationRunRequest request)
    {
        _logger.LogInformation("Creating {RunType} capitation run for period {Period}",
            request.RunType, request.CapitationPeriod);

        try
        {
            var run = await _runService.CreateRunAsync(request, request.CreatedBy);
            return CreatedAtAction(nameof(GetRunById), new { id = run.Id }, run);
        }
        catch (ArgumentException ex)
        {
            return BadRequest(new { error = ex.Message });
        }
    }

    /// <summary>
    /// Execute an existing capitation run (generates statements for all matching contracts)
    /// </summary>
    [HttpPost("{id}/execute")]
    [ProducesResponseType(typeof(CapitationRun), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult<CapitationRun>> ExecuteRun(string id)
    {
        _logger.LogInformation("Executing capitation run {RunId}", SanitizeForLog(id));

        try
        {
            var run = await _runService.ExecuteRunAsync(id);
            return Ok(run);
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { error = ex.Message });
        }
    }

    /// <summary>
    /// Get capitation run by ID
    /// </summary>
    [HttpGet("{id}")]
    [ProducesResponseType(typeof(CapitationRun), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<CapitationRun>> GetRunById(string id)
    {
        try
        {
            var run = await _runService.GetRunAsync(id);
            return Ok(run);
        }
        catch (InvalidOperationException ex)
        {
            return NotFound(new { error = ex.Message });
        }
    }

    /// <summary>
    /// List capitation runs with optional date range filter
    /// </summary>
    [HttpGet]
    [ProducesResponseType(typeof(IEnumerable<CapitationRun>), StatusCodes.Status200OK)]
    public async Task<ActionResult<IEnumerable<CapitationRun>>> GetRuns(
        [FromQuery] DateTime? from,
        [FromQuery] DateTime? to,
        [FromQuery] LineOfBusiness? lineOfBusiness = null)
    {
        var runs = await _runService.GetRunsAsync(from, to, lineOfBusiness);
        return Ok(runs);
    }

    /// <summary>
    /// Cancel a pending capitation run
    /// </summary>
    [HttpDelete("{id}")]
    [ProducesResponseType(StatusCodes.Status204NoContent)]
    [ProducesResponseType(StatusCodes.Status400BadRequest)]
    public async Task<ActionResult> CancelRun(string id)
    {
        try
        {
            await _runService.CancelRunAsync(id);
            return NoContent();
        }
        catch (InvalidOperationException ex)
        {
            return BadRequest(new { error = ex.Message });
        }
    }

    /// <summary>
    /// Get all statements generated by a capitation run
    /// </summary>
    [HttpGet("{id}/statements")]
    [ProducesResponseType(typeof(IEnumerable<CapitationStatement>), StatusCodes.Status200OK)]
    public async Task<ActionResult<IEnumerable<CapitationStatement>>> GetRunStatements(string id)
    {
        var statements = await _statementRepository.GetByRunIdAsync(id);
        return Ok(statements);
    }

    private static string SanitizeForLog(string? value)
    {
        if (string.IsNullOrEmpty(value))
            return string.Empty;
        return value.Replace("\r", string.Empty).Replace("\n", string.Empty);
    }
}
