using Microsoft.AspNetCore.Mvc;
using PaymentService.Models;
using PaymentService.Repositories;

namespace PaymentService.Controllers;

/// <summary>
/// Read-only access to batched 835 envelopes generated by PaymentRun
/// execution (capability 5.10). Phase 1 surface — no
/// regenerate/cancel/transmit endpoints; once an envelope is
/// generated it's an immutable artifact (matches 835 transmission
/// semantics). Phase 2 may add resend / correction workflows.
/// </summary>
[ApiController]
[Route("api/v1/era-envelopes")]
[Produces("application/json")]
public class EraEnvelopesController : ControllerBase
{
    private readonly IEraEnvelopeRepository _repository;
    private readonly ILogger<EraEnvelopesController> _logger;

    public EraEnvelopesController(
        IEraEnvelopeRepository repository,
        ILogger<EraEnvelopesController> logger)
    {
        _repository = repository;
        _logger = logger;
    }

    /// <summary>Single envelope metadata (excludes raw EDI body — use the <c>/edi</c> sub-resource).</summary>
    [HttpGet("{id}")]
    [ProducesResponseType(typeof(EraEnvelopeMetadata), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<ActionResult<EraEnvelopeMetadata>> GetById(string id)
    {
        var record = await _repository.GetByIdAsync(id);
        if (record == null)
            return NotFound(new { message = $"EraEnvelope {id} not found" });
        return Ok(EraEnvelopeMetadata.From(record));
    }

    /// <summary>
    /// Raw 835 EDI content as <c>text/plain</c>. Splitting EDI from
    /// metadata keeps clients that only need the file (transmission
    /// agents) from paying for JSON deserialization, and lets the
    /// metadata endpoint stay light when the EDI is large.
    /// </summary>
    [HttpGet("{id}/edi")]
    [ProducesResponseType(typeof(string), StatusCodes.Status200OK)]
    [ProducesResponseType(StatusCodes.Status404NotFound)]
    public async Task<IActionResult> GetEdi(string id)
    {
        var record = await _repository.GetByIdAsync(id);
        if (record == null)
            return NotFound(new { message = $"EraEnvelope {id} not found" });
        return Content(record.EdiContent, "text/plain");
    }

    /// <summary>
    /// Search envelopes by paymentRunId, tradingPartnerId, and/or
    /// reversalRunId (5.12b). Returns metadata only (no EDI bodies);
    /// use <c>GET /{id}/edi</c> for individual content.
    /// </summary>
    [HttpGet]
    [ProducesResponseType(typeof(IEnumerable<EraEnvelopeMetadata>), StatusCodes.Status200OK)]
    public async Task<ActionResult<IEnumerable<EraEnvelopeMetadata>>> Search(
        [FromQuery] string? paymentRunId = null,
        [FromQuery] string? tradingPartnerId = null,
        [FromQuery] string? reversalRunId = null)
    {
        var records = await _repository.SearchAsync(paymentRunId, tradingPartnerId, reversalRunId);
        return Ok(records.Select(EraEnvelopeMetadata.From));
    }
}

/// <summary>
/// Lightweight projection of <see cref="EraEnvelopeRecord"/> that
/// excludes the inline EDI body. Returned by GET /{id} and search
/// endpoints so clients reading lists don't ship 25KB of EDI per row.
/// </summary>
public class EraEnvelopeMetadata
{
    public string Id { get; set; } = string.Empty;
    public string PaymentRunId { get; set; } = string.Empty;
    public string? ReversalRunId { get; set; }
    public string TradingPartnerId { get; set; } = string.Empty;
    public int ClaimCount { get; set; }
    public decimal TotalPaymentAmount { get; set; }
    public string ControlNumber { get; set; } = string.Empty;
    public DateTime GeneratedAt { get; set; }
    public List<string> ClaimIds { get; set; } = new();
    public int EdiByteSize { get; set; }

    public static EraEnvelopeMetadata From(EraEnvelopeRecord record) => new()
    {
        Id = record.Id,
        PaymentRunId = record.PaymentRunId,
        ReversalRunId = record.ReversalRunId,
        TradingPartnerId = record.TradingPartnerId,
        ClaimCount = record.ClaimCount,
        TotalPaymentAmount = record.TotalPaymentAmount,
        ControlNumber = record.ControlNumber,
        GeneratedAt = record.GeneratedAt,
        ClaimIds = record.ClaimIds.ToList(),
        EdiByteSize = string.IsNullOrEmpty(record.EdiContent) ? 0 : System.Text.Encoding.UTF8.GetByteCount(record.EdiContent)
    };
}
