<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>ClaimsExaminerService</RootNamespace>
    <AssemblyName>claims-examiner-service</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../shared/CloudHealthOffice.Infrastructure/CloudHealthOffice.Infrastructure.csproj" />
    <ProjectReference Include="../shared/CloudHealthOffice.Events/CloudHealthOffice.Events.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.0" />
    <PackageReference Include="Confluent.Kafka" Version="2.6.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CloudHealthOffice.ClaimsExaminerService.Tests" />
  </ItemGroup>

</Project>
